// Generated by scripts/generate-extension-registry.mjs. Do not edit by hand.
// Run `npm run ext:registry` after adding or removing an extension folder.
import type { ExtensionManifest } from "@/lib/extension-api";

import calcManifest from "./calc/manifest";
import calendarManifest from "./calendar/manifest";
import dictionaryManifest from "./dictionary/manifest";
import stickersManifest from "./stickers/manifest";
import tasksManifest from "./tasks/manifest";

export const extensionManifests: readonly ExtensionManifest[] = [
  calcManifest,
  calendarManifest,
  dictionaryManifest,
  stickersManifest,
  tasksManifest,
];
