// Generated by scripts/generate-extension-registry.mjs. Do not edit by hand.
// Run `npm run ext:registry` after adding or removing an extension folder.
//
// Render modules are imported statically on both server and client, so they
// must stay light: definitions plus lazy component loaders (plan §4, §9).
import type { RenderModule } from "@/lib/extension-api";

import calcRender from "./calc/render";
import calendarRender from "./calendar/render";
import dictionaryRender from "./dictionary/render";
import stickersRender from "./stickers/render";
import tasksRender from "./tasks/render";

export const renderModules: readonly RenderModule[] = [
  calcRender,
  calendarRender,
  dictionaryRender,
  stickersRender,
  tasksRender,
];
