// Generated by scripts/generate-extension-registry.mjs. Do not edit by hand.
// Run `npm run ext:registry` after adding or removing an extension folder.
//
// Editor modules are referenced only through `import()`, so each is its own
// chunk, loaded for users who enabled the extension (plan §9).
import type { EditorModule, ExtensionManifest } from "@/lib/extension-api";

import calcManifest from "./calc/manifest";
import calendarManifest from "./calendar/manifest";
import dictionaryManifest from "./dictionary/manifest";
import stickersManifest from "./stickers/manifest";

export type ClientExtensionEntry = {
  manifest: ExtensionManifest;
  editor?: () => Promise<{ default: EditorModule }>;
};

export const clientExtensions: readonly ClientExtensionEntry[] = [
  {
    manifest: calcManifest,
  },
  {
    manifest: calendarManifest,
    editor: () => import("./calendar/editor"),
  },
  {
    manifest: dictionaryManifest,
    editor: () => import("./dictionary/editor"),
  },
  {
    manifest: stickersManifest,
    editor: () => import("./stickers/editor"),
  },
];
