// Generated by scripts/generate-extension-registry.mjs. Do not edit by hand.
// Run `npm run ext:registry` after adding or removing an extension folder.
import "server-only";

import type { ExtensionManifest } from "@/lib/extension-api";
import type { ExtensionServerModule } from "@/lib/extension-api/server";

import calcManifest from "./calc/manifest";
import calendarManifest from "./calendar/manifest";
import dictionaryManifest from "./dictionary/manifest";
import stickersManifest from "./stickers/manifest";
import tasksManifest from "./tasks/manifest";

import calcServer from "./calc/server";
import calendarServer from "./calendar/server";
import dictionaryServer from "./dictionary/server";
import stickersServer from "./stickers/server";
import tasksServer from "./tasks/server";

export type ServerExtensionEntry = {
  manifest: ExtensionManifest;
  server: ExtensionServerModule | null;
};

export const serverExtensions: readonly ServerExtensionEntry[] = [
  { manifest: calcManifest, server: calcServer },
  { manifest: calendarManifest, server: calendarServer },
  { manifest: dictionaryManifest, server: dictionaryServer },
  { manifest: stickersManifest, server: stickersServer },
  { manifest: tasksManifest, server: tasksServer },
];
